apiVersion: v1
kind: Secret
metadata:
  name: edgeguard-secrets
  namespace: edgeguard
type: Opaque
stringData:
  JWT_SECRET: "k8s-prod-jwt-secret-key-change-me"
  EDGEGUARD_SERVICE_TOKEN: "k8s-prod-service-token-change-me"
